### ISSUE TITLE
texlive install script

### ISSUE THREAD

**Issue by blauret** [ilg-ul/opt-install-scripts#2]
It seems to me the install-texlive.sh is out of date. The install-tl-unx.tar.gz was updated today and it looks like a whole bunch of collection names and options have been updated. 

Currently it fails to install for me. I was able to modify the collection and get the script running tough.

**Comment by ilg-ul** [comment]
could you provide a patch to see the changes?

**Comment by ilg-ul** [comment]
I think a safer solution would be to update the script to avoid using the latest release, and use a specific release, like 2016, so that the list of packages will remain valid.

**Comment by blauret** [comment]
[texlive_patch.txt](https://github.com/ilg-ul/opt-install-scripts/files/1115270/texlive_patch.txt)

here it is.

**Comment by blauret** [comment]
I don't really know what I'm doing when it comes to configure texlive. the installation is "working", but I'm not sure there's no features loss with this.

**Comment by ilg-ul** [comment]
> texlive_patch.txt

thank you. next week I plan to install texlive on a new machine, so I'll need to update the script.

> I don't really know what I'm doing when it comes to configure texlive

neither do I, last time it took me quite some time and several interactions with the tex maintainers to figure out the details.

**Comment by ilg-ul** [comment]
since I had no time to thoroughly investigate the differences between 2016 and 2017, I updated the script to explicitly use the 2016 version.

if needed and time permitting, I'll update it to the 2017 version.

**Comment by blauret** [comment]
I did not test, but if it works for you, I'm happy to close it. 

I was interested in using the build scripts to rebuild openocd, which is successful for me with the patch provided. Anyhow this is a good solution for me too.

**Comment by ilg-ul** [comment]
based on my experience with package managers, it is always prefered to have an install script explicitly refer to a given version, since, once details fixed, that script will always result in the same installed program. it may not be the latest and greatest, but if it was functional once, it should remain functional.
